"""Pure packing logic - import analysis and runner rendering, no I/O.

The script packer turns a Python entry script plus the local modules it imports into a
single self-extracting ``.ps1``.  Everything in this module is a pure function over text:
parse a module's imports, classify each one, and substitute a rendered payload into the
runner template.  Reading files, building the archive, and writing the result all live in
:mod:`pwshpy.adapters.native.packer`.

Two design points are load-bearing:

* **Only local modules are embedded.** The standard library travels with the interpreter
  uv provisions, and third-party distributions come from the entry's PEP 723 block or
  ``--with``.  An import name is never guessed at as a distribution name (``yaml`` is
  PyYAML, ``cv2`` is opencv-python); guessing would install the wrong package silently.
* **The argument vector travels out of band.** Windows PowerShell 5.1 re-quotes arguments
  when it calls a native executable, mangling empty strings and embedded quotes, and only
  7.3+ fixed it.  The runner therefore base64-encodes the argument vector as JSON into an
  environment variable and :data:`SHIM_SOURCE` rebuilds ``sys.argv`` from it, so the packed
  script sees exactly what the caller typed on every host.

Contents:
    * :func:`iter_import_candidates` - dotted module names a source file imports.
    * :func:`classify_import` - stdlib / local / external for one dotted name.
    * :func:`candidate_relative_paths` - the file paths a dotted name may live at.
    * :func:`extract_script_metadata` - lift the entry's PEP 723 block onto the shim.
    * :func:`render_shim` - the generated ``__main__`` shim for one entry.
    * :func:`render_runner` - substitute a payload into the runner template.
    * :func:`chunk_base64` - wrap a base64 blob to a fixed line width.
"""

from __future__ import annotations

import ast
from collections.abc import Iterator, Sequence

from .enums import ImportKind
from .errors import PackError

#: Name of the generated shim module inside the payload.  Dunder-prefixed so it cannot
#: collide with a user module, and so an ``import *`` never picks it up.
SHIM_MODULE = "__pwshpy_pack_main__.py"

#: Environment variable carrying the encoded argument vector from runner to shim.
ARGV_ENV_VAR = "PWSHPY_PACK_ARGV"

#: Version tag leading the encoded argument vector.  Without it a single empty-string
#: argument would encode to an empty blob, indistinguishable from "no arguments at all".
ARGV_ENCODING_TAG = "v1"

#: Placeholders the runner template exposes for substitution.  Distinctive enough that
#: they cannot occur in hand-written PowerShell by accident.
_PLACEHOLDERS = (
    "@@PWSHPY_PAYLOAD_B64@@",
    "@@PWSHPY_PAYLOAD_SHA256@@",
    "@@PWSHPY_ENTRY@@",
    "@@PWSHPY_UV_ARGS@@",
    "@@PWSHPY_FILE_HASHES@@",
    "@@PWSHPY_SHIM@@",
    "@@PWSHPY_ARGV_ENV@@",
)

#: The generated ``__main__`` shim.  It rebuilds ``sys.argv`` from the out-of-band
#: environment variable, then executes the real entry as ``__main__`` so ``if __name__ ==
#: "__main__"`` fires exactly as it would for a direct ``python entry.py`` run.
#:
#: ``sys.argv[0]`` is set to the *entry* path, not the shim's, so that a packed script
#: calling ``ps.elevate()`` (which re-execs ``sys.executable`` + ``sys.argv``) reproduces
#: the invocation faithfully - the elevated child runs the entry directly, bypassing both
#: the shim and uv, against the environment uv already built.
SHIM_SOURCE = '''{metadata}"""Generated by pwshpy pack - rebuilds argv, then runs the entry as __main__."""

import base64
import os
import runpy
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ENTRY = os.path.join(_HERE, {entry!r})


def _argv_from_environment():
    """Decode the out-of-band argument vector written by the PowerShell runner.

    Each argument is UTF-8 then base64, joined with "|" behind a version tag, so an
    empty-string argument survives and no separator can occur inside a piece.
    """
    blob = os.environ.pop({env_var!r}, "")
    if not blob:
        return []
    tag, separator, rest = blob.partition("|")
    if tag != {tag!r}:
        raise SystemExit("pwshpy pack: unsupported argument encoding " + tag)
    if not separator:
        return []
    return [base64.b64decode(piece).decode("utf-8") for piece in rest.split("|")]


sys.argv = [_ENTRY] + _argv_from_environment()
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)
runpy.run_path(_ENTRY, run_name="__main__")
'''


def iter_import_candidates(
    source: str, *, module_package: Sequence[str] = (), filename: str = "<pack>"
) -> Iterator[str]:
    """Yield the dotted module names ``source`` imports, resolving relative imports.

    Both halves of ``from pkg import name`` are yielded (``pkg`` and ``pkg.name``), because
    ``name`` may be either a submodule to embed or an attribute of the package; the caller
    resolves which by looking for a file.  Parent packages of a dotted import are yielded
    too, since importing ``a.b.c`` executes ``a/__init__.py`` and ``a/b/__init__.py``.

    Args:
        source: Python source text.
        module_package: Package parts the module lives in, used to anchor relative imports
            (``("pkg",)`` for ``pkg/mod.py``).
        filename: Name used in the error message when the source does not parse.

    Raises:
        PackError: If ``source`` is not valid Python.

    Example:
        >>> sorted(iter_import_candidates("import a.b\\nfrom c import d"))
        ['a', 'a.b', 'c', 'c.d']
        >>> sorted(iter_import_candidates("from . import sib", module_package=("pkg",)))
        ['pkg', 'pkg.sib']
        >>> sorted(iter_import_candidates("from .. import top", module_package=("a", "b")))
        ['a', 'a.top']
    """
    try:
        tree = ast.parse(source, filename=filename)
    except SyntaxError as exc:
        raise PackError(f"{filename} is not valid Python: {exc}") from exc
    seen: set[str] = set()
    for node in ast.walk(tree):
        for dotted in _node_candidates(node, tuple(module_package)):
            if dotted and dotted not in seen:
                seen.add(dotted)
                yield dotted


def _node_candidates(node: ast.AST, package: tuple[str, ...]) -> Iterator[str]:
    """Yield the dotted names one import node contributes (with their parent packages)."""
    if isinstance(node, ast.Import):
        for alias in node.names:
            yield from _with_parents(alias.name)
    elif isinstance(node, ast.ImportFrom):
        base = _resolve_from_base(node, package)
        if base is None:
            return
        if base:
            yield from _with_parents(base)
        for alias in node.names:
            if alias.name != "*":
                yield ".".join(filter(None, (base, alias.name)))


def _resolve_from_base(node: ast.ImportFrom, package: tuple[str, ...]) -> str | None:
    """Resolve the base package of a ``from ... import`` node, or ``None`` if it escapes.

    A relative import climbs ``level - 1`` packages from the module's own package.  One
    that climbs past the pack root cannot be embedded, so it is dropped rather than
    silently resolved to the wrong file.
    """
    if not node.level:
        return node.module or ""
    climb = node.level - 1
    if climb > len(package):
        return None
    anchor = package[: len(package) - climb] if climb else package
    return ".".join((*anchor, node.module)) if node.module else ".".join(anchor)


def _with_parents(dotted: str) -> Iterator[str]:
    """Yield ``a``, ``a.b``, ``a.b.c`` for ``a.b.c`` - importing a submodule runs its parents."""
    parts = dotted.split(".")
    for index in range(1, len(parts) + 1):
        yield ".".join(parts[:index])


def classify_import(dotted: str, *, stdlib_names: frozenset[str], local_names: frozenset[str]) -> ImportKind:
    """Classify a dotted import as stdlib, local, or external.

    ``local_names`` wins over ``stdlib_names``: a file sitting next to the entry shadows a
    standard-library module of the same name at runtime, so the pack must carry it too.

    Example:
        >>> std, loc = frozenset({"json"}), frozenset({"helper"})
        >>> classify_import("json.decoder", stdlib_names=std, local_names=loc).value
        'stdlib'
        >>> classify_import("helper", stdlib_names=std, local_names=loc).value
        'local'
        >>> classify_import("rich.console", stdlib_names=std, local_names=loc).value
        'external'
    """
    if dotted in local_names:
        return ImportKind.LOCAL
    if dotted.split(".", 1)[0] in stdlib_names:
        return ImportKind.STDLIB
    return ImportKind.EXTERNAL


def extract_script_metadata(source: str) -> str:
    """Return the entry's PEP 723 ``script`` block verbatim, or ``""`` if it has none.

    uv reads inline metadata from the file it is asked to run, and a pack runs the
    generated shim rather than the entry directly, so the block has to travel onto the
    shim - otherwise the declared dependencies and ``requires-python`` are silently
    ignored and the packed script fails on its first third-party import.

    Only the first block counts, matching PEP 723: a second one is a spec error, and
    duplicating it onto the shim would make uv reject the run outright.

    Example:
        >>> src = '# /// script\\n# dependencies = ["rich"]\\n# ///\\nimport rich\\n'
        >>> extract_script_metadata(src)
        '# /// script\\n# dependencies = ["rich"]\\n# ///\\n'
        >>> extract_script_metadata("import os\\n")
        ''
    """
    lines = source.splitlines()
    for index, line in enumerate(lines):
        if line.rstrip() != "# /// script":
            continue
        for end in range(index + 1, len(lines)):
            stripped = lines[end].rstrip()
            if stripped == "# ///":
                return "\n".join(lines[index : end + 1]) + "\n"
            if not (stripped == "#" or stripped.startswith("# ")):
                break
        raise PackError("the entry's PEP 723 script block is not closed by a '# ///' line")
    return ""


def render_shim(*, entry: str, metadata: str) -> str:
    """Render the generated ``__main__`` shim that fronts ``entry`` inside a pack.

    Example:
        >>> shim = render_shim(entry="tool.py", metadata="")
        >>> "runpy.run_path(_ENTRY" in shim and "'tool.py'" in shim
        True
        >>> render_shim(entry="t.py", metadata="# /// script\\n# ///\\n").startswith("# /// script")
        True
    """
    return SHIM_SOURCE.format(
        metadata=metadata,
        entry=entry,
        env_var=ARGV_ENV_VAR,
        tag=ARGV_ENCODING_TAG,
    )


def candidate_relative_paths(dotted: str) -> tuple[str, str]:
    """Return the ``(module.py, package/__init__.py)`` paths a dotted name may live at.

    Example:
        >>> candidate_relative_paths("pkg.helper")
        ('pkg/helper.py', 'pkg/helper/__init__.py')
    """
    stem = dotted.replace(".", "/")
    return f"{stem}.py", f"{stem}/__init__.py"


def chunk_base64(blob: str, width: int = 120) -> str:
    """Wrap a base64 blob to ``width`` characters per line for embedding in a here-string.

    Example:
        >>> chunk_base64("abcdef", width=2)
        'ab\\ncd\\nef'
        >>> chunk_base64("", width=4)
        ''
    """
    if width < 1:
        raise PackError(f"base64 line width must be positive, got {width}")
    return "\n".join(blob[index : index + width] for index in range(0, len(blob), width))


def render_runner(
    template: str,
    *,
    payload_b64: str,
    payload_sha256: str,
    entry: str,
    uv_args: Sequence[str],
    file_hashes: Sequence[tuple[str, str]],
) -> str:
    """Substitute a payload into the runner template, returning the finished ``.ps1`` text.

    Args:
        template: The runner template text, carrying every ``@@PWSHPY_*@@`` placeholder.
        payload_b64: Base64 of the payload zip, already line-wrapped.
        payload_sha256: Hex digest of the payload zip; keys the extraction cache.
        entry: Archive-relative path of the entry script.
        uv_args: Extra arguments spliced into the ``uv run`` invocation (``--with`` pins).
        file_hashes: ``(sha256, relative_path)`` pairs the runner verifies before running.

    Raises:
        PackError: If the template is missing a placeholder, which would ship a runner with
            a literal ``@@PWSHPY_...@@`` in it.

    Example:
        >>> tpl = "P=@@PWSHPY_PAYLOAD_B64@@ S=@@PWSHPY_PAYLOAD_SHA256@@ E=@@PWSHPY_ENTRY@@ " \\
        ...       "U=@@PWSHPY_UV_ARGS@@ H=@@PWSHPY_FILE_HASHES@@ M=@@PWSHPY_SHIM@@ V=@@PWSHPY_ARGV_ENV@@"
        >>> render_runner(tpl, payload_b64="Ym9keQ==", payload_sha256="ab12", entry="t.py",
        ...               uv_args=["--with", "rich"], file_hashes=[("ff", "t.py")])
        "P=Ym9keQ== S=ab12 E=t.py U='--with','rich' H=ff *t.py M=__pwshpy_pack_main__.py V=PWSHPY_PACK_ARGV"
    """
    missing = [token for token in _PLACEHOLDERS if token not in template]
    if missing:
        raise PackError(f"runner template is missing placeholder(s): {', '.join(missing)}")
    replacements = {
        "@@PWSHPY_PAYLOAD_B64@@": payload_b64,
        "@@PWSHPY_PAYLOAD_SHA256@@": payload_sha256,
        "@@PWSHPY_ENTRY@@": entry,
        "@@PWSHPY_UV_ARGS@@": _powershell_string_array(uv_args),
        "@@PWSHPY_FILE_HASHES@@": "\n".join(f"{digest} *{path}" for digest, path in file_hashes),
        "@@PWSHPY_SHIM@@": SHIM_MODULE,
        "@@PWSHPY_ARGV_ENV@@": ARGV_ENV_VAR,
    }
    rendered = template
    for token, value in replacements.items():
        rendered = rendered.replace(token, value)
    return rendered


def _powershell_string_array(values: Sequence[str]) -> str:
    """Render values as a PowerShell single-quoted list, doubling embedded single quotes.

    Single-quoted PowerShell strings are literal - no ``$`` expansion, no backtick escapes -
    so the only character needing care is the quote itself.

    Example:
        >>> _powershell_string_array(["--with", "it's"])
        "'--with','it''s'"
        >>> _powershell_string_array([])
        ''
    """
    return ",".join("'" + value.replace("'", "''") + "'" for value in values)


__all__ = [
    "ARGV_ENCODING_TAG",
    "ARGV_ENV_VAR",
    "SHIM_MODULE",
    "SHIM_SOURCE",
    "candidate_relative_paths",
    "chunk_base64",
    "classify_import",
    "extract_script_metadata",
    "iter_import_candidates",
    "render_runner",
    "render_shim",
]
